# Use postgres/example user/password credentials
version: '3.8'

services:
  testdb_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alexandria
    ports:
      - 5432:5432
    volumes:
      - './src/model/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql'
      - './src/model/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql'
      - './src/model/init-test-db.sh:/docker-entrypoint-initdb.d/03-init-test-db.sh'
